version: "3.8"

services:
  letterboxd-sync:
    build: .
    container_name: letterboxd-sync
    restart: unless-stopped
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./sync_state.json:/app/sync_state.json
      # Optional: Mount a local file for proxies.txt if you use it
      # - ./proxies.txt:/app/proxies.txt:ro
    network_mode: host