version: "3.1"
name: letterboxd_jellyfin

services:
  cron:
    container_name: cron
    image: registry.diikstra.fr/letterboxd-jellyfin-cron:${IMAGE_TAG}
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped